// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package numbers

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NumServiceClient is the client API for NumService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NumServiceClient interface {
	Sum(ctx context.Context, opts ...grpc.CallOption) (NumService_SumClient, error)
}

type numServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNumServiceClient(cc grpc.ClientConnInterface) NumServiceClient {
	return &numServiceClient{cc}
}

func (c *numServiceClient) Sum(ctx context.Context, opts ...grpc.CallOption) (NumService_SumClient, error) {
	stream, err := c.cc.NewStream(ctx, &NumService_ServiceDesc.Streams[0], "/numbers.NumService/Sum", opts...)
	if err != nil {
		return nil, err
	}
	x := &numServiceSumClient{stream}
	return x, nil
}

type NumService_SumClient interface {
	Send(*NumRequest) error
	CloseAndRecv() (*NumResponse, error)
	grpc.ClientStream
}

type numServiceSumClient struct {
	grpc.ClientStream
}

func (x *numServiceSumClient) Send(m *NumRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *numServiceSumClient) CloseAndRecv() (*NumResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(NumResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NumServiceServer is the server API for NumService service.
// All implementations must embed UnimplementedNumServiceServer
// for forward compatibility
type NumServiceServer interface {
	Sum(NumService_SumServer) error
	mustEmbedUnimplementedNumServiceServer()
}

// UnimplementedNumServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNumServiceServer struct {
}

func (UnimplementedNumServiceServer) Sum(NumService_SumServer) error {
	return status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedNumServiceServer) mustEmbedUnimplementedNumServiceServer() {}

// UnsafeNumServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NumServiceServer will
// result in compilation errors.
type UnsafeNumServiceServer interface {
	mustEmbedUnimplementedNumServiceServer()
}

func RegisterNumServiceServer(s grpc.ServiceRegistrar, srv NumServiceServer) {
	s.RegisterService(&NumService_ServiceDesc, srv)
}

func _NumService_Sum_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NumServiceServer).Sum(&numServiceSumServer{stream})
}

type NumService_SumServer interface {
	SendAndClose(*NumResponse) error
	Recv() (*NumRequest, error)
	grpc.ServerStream
}

type numServiceSumServer struct {
	grpc.ServerStream
}

func (x *numServiceSumServer) SendAndClose(m *NumResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *numServiceSumServer) Recv() (*NumRequest, error) {
	m := new(NumRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NumService_ServiceDesc is the grpc.ServiceDesc for NumService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NumService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "numbers.NumService",
	HandlerType: (*NumServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sum",
			Handler:       _NumService_Sum_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "numbers.proto",
}
